### ISSUE TITLE
Determine Idle States

### ISSUE THREAD

**Issue by watfordjc** [watfordjc/SleepyWindows#2]
# Feature Branch

Current feature branch for this issue: [not created yet](../tree/feature/issue-12345/projectname-branchversion).

## Progress

- [x] Subscribe to changes in user presence events.
- [x] Check idle state using timers based on user presence.
- [ ] Check idle state when user presence changes, when power source changes, and when battery level decreases.
- [ ] Determine idle state.
    - [x] User is absent.
    - [ ] System is idle.
    - [x] No application has made a power request requiring the display remain turned on.

---

# Background

Windows should go to sleep following the current power configuration profile. The relevant profile settings rely on the definition of the word "idle".

## Definition of Idle

Windows uses three things to determine if the computer is idle.
1. User absence.
    * No human interface device input.
2. Resource usage.
    * All processors have been idle for more than 90% of the time (80% for Windows 8 and later).
    * All disks have been idle for more than 90% of the time (80% for Windows 8 and later).
3. Application overrides (```SetThreadExecutionState```).
    * Flag ```ES_CONTINUOUS```: the other flags in the call are permanently on until cleared in a subsequent call containing the ```ES_CONTINUOUS``` flag.
    * Flag ```ES_DISPLAY_REQUIRED```: The display idle timer is reset.
    * Flag ```ES_AWAYMODE_REQUIRED```: Must be combined with ```ES_CONTINUOUS```. Enable away mode - i.e. the application is doing something important and should continue doing it even if the user is away.
    * Flag ```ES_SYSTEM_REQUIRED```: The system idle timer is reset.

User absence and resource usage are tracked automatically by Windows. For Windows 7 and 8 (non-server), task scheduler uses the following rules.

### Windows 7 Task Scheduler
1. Check idle state every 15 minutes.
2. The computer is idle if:
    1. The user is absent if there has been no user input since the last idle check.
    2. All processors and disks have been idle for more than 90% of the time since the last idle check.
    3. No applications have set the ```ES_DISPLAY_REQUIRED``` flag.

### Windows 8 Task Scheduler
1. User presence is handled by the OS's power subsystem - by default, the user is absent if there has been no user input for 4 minutes.
2. Check idle state every 30 seconds if the user is absent, or every 10 minutes if user is present.
3. Check idle state when user presence state changes, when power source changes, and (when running on battery power) when the battery level changes.
4. The computer is idle if:
    1. The user is absent.
    2. All processors and disks have been idle for more than 80% of the time since the last idle check.
    3. No applications have set the ```ES_DISPLAY_REQUIRED``` flag.

## Idle In Practice

Based on [the documentation for Task idle conditions](https://docs.microsoft.com/en-gb/windows/win32/taskschd/task-idle-conditions), the main difference between Windows 7 and Windows 8 is the use of more granular timers.

Under Windows 7, Task Scheduler's idle check timer is rather simple. Imagine a ```DateTime``` variable being set by a ```Timer``` that fires every 900 seconds. The timer starts when the system starts, and gets reset whenever an application uses the ```ES_SYSTEM_REQUIRED``` flag.

Under Windows 8, Task Scheduler's idle check timer is a little more detailed. Imagine a ```DateTime``` variable being set by a ```Timer```. If the user is present, ```Timer.Interval= 600000; // 10 minutes```. If the user is present, ```Timer.Interval = 30000; // 30 seconds```. The timer starts when the system starts, and gets reset whenever an application uses the ```ES_SYSTEM_REQUIRED``` flag. There are 3 events that bypass the timer, one of which also changes the timer's interval.

To continue the code analogy, the ```DateTime``` variable is combined with a ```bool```, with the boolean value being set to true if the computer is idle (false if it is not), and the timestamp being updated with the current time whenever the boolean value changes. When the boolean is true, things can happen based on much time has passed since the timestamp.

## The Issue

What we need to do is mirror what Task Scheduler does.

The point of this issue is to aid in determining *why* the computer isn't being detected as idle. To do that, we need to get the idle state.

Task Scheduler has the ```IIdleTrigger``` interface that is called whenever the computer enters an idle state. We can probably use that to detect the computer determining it has become idle.

```WM_POWERBROADCAST``` events can contain a ```POWERBROADCAST_SETTING``` structure, which contains a ```GUID``` for a [Power Setting GUID](https://docs.microsoft.com/en-us/windows/win32/power/power-setting-guids). This covers some of the things needed to perform an idle check, such as ```GUID_GLOBAL_USER_PRESENCE``` (user absence) and ```GUID_SYSTEM_AWAYMODE``` (enabling/disabling ```ES_AWAYMODE_REQUIRED```).

The ```CallNtPowerInformation``` function can obtain other relevant information for an idle check, such as using the function with ```SystemExecutionState``` to get the value of ```ES_SYSTEM_REQUIRED | ES_DISPLAY_REQUIRED | ES_USER_PRESENT```, and ```SystemPowerInformation``` to possibly get information about the system idle timer.

The ```SYSTEM_POWER_INFORMATION``` struct has members that sound familiar: ```MaxIdlenessAllowed``` sounds like 80%/90%, ```Idleness``` is the current idle percentage, and ```TimeRemaining``` says something about time left in an idle timer. ```DISK_PERFORMANCE``` has an ```IdleTime``` member. I'm not sure if these are suitable or if I'll need to use WMI.

CPU and disk idle time are the one thing I'm unsure of. The other things used to determine if a Windows system is idle appear to be accessible to an application/service.

**Comment by watfordjc** [comment]
## Away Mode

Away Mode is a bit hard for me to grasp.

There is an event that can be subscribed to for when Away Mode is entered/exited, and there is also a way to determine if applications can make a power request requiring Away Mode.

From some limited testing, there is no documented Win32 way of determining if any applications have made an Away Mode power request.

Away Mode is an alternative to S3 Sleep, but isn't technically a power saving feature. I don't believe there is a way to configure power settings to set Away Mode as the thing that happens when the computer has been idle for however many minutes as there are for Sleep/Hibernate/Power Off/etc. - Away Mode is not listed as an option in the ```POWER_ACTION``` enum.

From what I can piece together from the documentation and some forum threads, Away Mode is entered/exited if a power request for Away Mode has been made by an application *and* the user specifically requests the computer go to sleep (whether by the Start Menu, or the Sleep/Power/Lid button).

I'm not yet sure if an Away Mode request needs to be combined with another request type, such as System or Execution.

When Away Mode is entered/exited, I believe a ```GUID_SYSTEM_AWAYMODE``` (```PowerNotificationGuids.SystemAwayMode```) event is fired.

I also believe that while in Away Mode, user presence is set to ```USER_ACTIVITY_PRESENCE.PowerUserNotPresent``` given the enum only has 4 values and I know what the other 3 are for: ```USER_ACTIVITY_PRESENCE.PowerUserPresent``` (there has been user input in the last 4 minutes), ```USER_ACTIVITY_PRESENCE.PowerUserInactive``` (there has been no user input for 4 minutes), and ```USER_ACTIVITY_PRESENCE.PowerUserInvalid``` (the maximum value of the enum).

Microsoft tend to have an Invalid or Reserved value in enums for displaying an error message for indexes greater than or equal to the "Invalid" enum (```USER_ACTIVITY_PRESENCE.PowerUserInvalid```, ```POWER_ACTION.PowerActionReserved```, etc.). Sometimes the documentation lists two things for the same enum value, with the Reserved1/Invalid listing being for an older version and the Reserved2/Invalid listing being a new maximum value, requiring the deletion of Reserved1 when implementing in C#.

Based on some debug testing (starting SleepyWindows that makes an Away Mode power request upon form loading and releases the request after an hour, clicking Sleep in the Start/Power menu, putting my mouse down without moving it, waiting a couple of minutes, and pressing the Ctrl key), this is how it works:
```
'SleepyWindows.exe' (CoreCLR: clrhost): Loaded ...
Power settings changed: PowerNotificationGuids/Idle Background Task
Power settings changed: PowerNotificationGuids/System Away Mode
Entering Away Mode
Power settings changed: PowerNotificationGuids/Global User Presence
User Presence: Inactive
Idle check at 30/07/2021 17:00:53
Idle check at 30/07/2021 17:01:23
Power settings changed: PowerNotificationGuids/Idle Background Task
Idle check at 30/07/2021 17:01:54
Idle check at 30/07/2021 17:02:24
Power settings changed: PowerNotificationGuids/Idle Background Task
Power settings changed: PowerNotificationGuids/Global User Presence
User Presence: Present
Idle check at 30/07/2021 17:02:38
Power settings changed: PowerNotificationGuids/System Away Mode
Exiting Away Mode
Power settings changed: PowerNotificationGuids/Idle Background Task
```

Power consumption was about on par with turning off the monitor.

My only incorrect assumption is that of user presence, where it switches to ```USER_ACTIVITY_PRESENCE.PowerUserInactive``` upon entering Away Mode. I haven't determined when user presence is ever set to ```USER_ACTIVITY_PRESENCE.PowerUserNotPresent```. Maybe at the login screen with no logged in users, maybe on a server, but it doesn't appear Away Mode sets it.

**Comment by watfordjc** [comment]
## Issue Task List

I haven't yet created a task list for this issue. This issue is rather simple: determine if the computer is idle.

### Windows 8 Task Scheduler
1. User presence is handled by the OS's power subsystem - by default, the user is absent if there has been no user input for 4 minutes.
2. Check idle state every 30 seconds if the user is absent, or every 10 minutes if user is present.
3. Check idle state when user presence state changes, when power source changes, and (when running on battery power) when the battery level changes.
4. The computer is idle if:
    1. The user is absent.
    2. All processors and disks have been idle for more than 80% of the time since the last idle check.
    3. No applications have set the ```ES_DISPLAY_REQUIRED``` flag.

### Sleepy Windows
1. Subscribe to changes in user presence events (subscribing also fires a user presence event).
2. Check idle state based on time.
    1. When user presence changes, set the tag of a dispatch timer with a 1 second tick to the idle check timer value in seconds (i.e. every 30 seconds, or every 10 minutes), call ```IdleCheck()``` (which adds the tag's number of seconds to a ```DateTime``` variable storing the time of the next scheduled call), and start/reset the timer.
    2. On every tick of the dispatch timer (approximately every 1 second), call ```IdleCheck()``` if the next scheduled call to it is now or in the past (```<= 0``` seconds). If the computer has now become idle, ```IdleCheck()``` sets a ```DateTime``` variable to the timestamp of when it became idle.
3. User presence changes calling ```IdleCheck()``` are covered in (2). Also call ```IdleCheck()``` whenever ```GetPowerProfile()``` is called:
    1. Call ```GetPowerProfile()``` on ```SystemEvents.UserPreferenceChanged``` (```if (e.Category == UserPreferenceCategory.Power)```).
    2.  Call ```GetPowerProfile()``` on ```SystemEvents.PowerModeChanged``` (```if (e.Mode == PowerModes.StatusChange)```).
        1. TODO: Limit calls to ```IdleCheck()``` on ```StatusChange``` - shouldn't be called if the only change is the battery charge level has increased.
4. In ```IdleCheck()```:
    1. Check ```POWER_INFORMATION_LEVEL.SystemExecutionState``` for ```EXECUTION_STATE.ES_USER_PRESENT```.
    2. Call ```SystemIdleCheck()```.
        1. TODO: Subtracting the value of system idle timer (```SystemPowerInformation.TimeRemaining``` - appears to have 30 second decrements) from the idle timeout (```PowerSchemeSettingGuids.Sleep.StandbyIdleTimeout```) will give how long the "system" has been idle.
        2. TODO: If the result is not zero, the "system" is idle.
        3. TODO: The system idle timer goes negative if the computer has been idle for longer than the idle timeout, so the logic will need to make sure the subtraction becomes addition.
    3. Check ```POWER_INFORMATION_LEVEL.SystemExecutionState``` for ```EXECUTION_STATE.ES_DISPLAY_REQUIRED```.

### Task List

- [x] Subscribe to changes in user presence events.
- [x] Check idle state using timers based on user presence.
- [ ] Check idle state when user presence changes, when power source changes, and when battery level decreases.
- [ ] Determine idle state.
    - [x] User is absent.
    - [ ] System is idle.
    - [x] No application has made a power request requiring the display remain turned on.
